#include "stdafx.h"
#include <stdio.h>
#include <stm8s_exti.h>
#include <LIS3DH.h>
//#include <intrinsics.h>
//#include <iostm8s103f3.h>
//#include <stdafx.h>


void delay(uint16_t time){
  uint16_t i;
  uint16_t j;

  for (i=0; i<200; i++){
    for(j=0; j<time;j++){
      nop();
    }
  }
}

//  Process the interrupt generated by the pressing of the button on PD4.
#pragma vector = 8
__interrupt void EXTI_PORTD_IRQHandler(void)
{
    actuate(70);
    blink_led(1,5000);
    SPI_read(0x31);    
}

int main( void ){
    
    //Configure Input/Output Pins
    GPIO_DeInit(GPIOA);
    GPIO_DeInit(GPIOD);
    GPIO_DeInit(GPIOB);
    
    GPIO_Init(GPIOA, GPIO_PIN_2, GPIO_MODE_OUT_PP_LOW_FAST);                   // LED
    GPIO_Init(GPIOD, GPIO_PIN_4, GPIO_MODE_IN_FL_IT);                           // Interrupt Pin PD4
    GPIO_Init(GPIOB, GPIO_PIN_4, GPIO_MODE_OUT_OD_LOW_SLOW);                    //Mosfet GATE

    // Initialize SPI
    SPI_DeInit();
    init_spi();
    
    // Initialize LIS3DH
    init_acc();

    //Configure Interrupt Modes
    tap2();
    read_acc();
    //freefall_electicimp();
    
    //  Set up the interrupt.
    EXTI_SetExtIntSensitivity (EXTI_PORT_GPIOD, EXTI_SENSITIVITY_FALL_ONLY);
    __enable_interrupt();
    
    GPIO_WriteLow(GPIOB, GPIO_PIN_4);
    GPIO_WriteLow(GPIOA, GPIO_PIN_2);
    blink_led(5, 100);
    delay(500);
    
    while(1){
     
     read_acc();
//     halt();                 // Halt Mode
    }
}


void init_acc(){
  
  uint8_t dataToWrite = 0; //Start Fresh!
  
  //dataToWrite |= 0x4 << 4; //ODR of 50Hz
  dataToWrite |= 0x5 << 4; //ODR of 100Hz
  dataToWrite |= 0x7; //Enable all axes
  SPI_write(LIS3DH_CTRL_REG1, dataToWrite);
//  if(SPI_read(LIS3DH_CTRL_REG1) !=  dataToWrite)
  
  dataToWrite = 0x80; // Range of 2g + other parameters
  SPI_write(LIS3DH_CTRL_REG4, dataToWrite);
//  if(SPI_read(LIS3DH_CTRL_REG4) !=  dataToWrite)
//    printf("ERROR2");
//  
  dataToWrite = 0x80; //ADC enable
  SPI_write(LIS3DH_TEMP_CFG_REG, dataToWrite);
//  if(SPI_read(LIS3DH_TEMP_CFG_REG) !=  dataToWrite)
//    printf("ERROR3");
}

void read_acc(){
  
  // read in the 3 axis data, each one is 14 bits
  // print the data to terminal
  uint8_t result[6];
  result[0] = SPI_read(0x28);  
  result[1] = SPI_read(0x29);  
  result[2] = SPI_read(0x2A);  
  result[3] = SPI_read(0x2B);  
  result[4] = SPI_read(0x2C);  
  result[5] = SPI_read(0x2D); 
  
  int x = (int16_t)result[0] | (int16_t)(result[1] << 8) ;
  float x1 = x / 4096.0/4;
  
  int y = (int16_t)result[2] | (int16_t)(result[3] << 8);
  float y1 = y / 4096.0/4;
  
  int z = (int16_t)result[4] | (int16_t)(result[5] << 8);
  float z1 = z / 4096.0/4;
  
  float sense = 0.3;
  if(z1 < sense && x1 < sense && y1 < sense){
    if(z1 > -sense && x1 > -sense && y1 > -sense){  
      actuate(50);         //printf("x : %.2f      y : %.2f        z : %.2f\n", x1, y1, z1);
      blink_led(3,1500);
    }
  }
}

void SPI_writeBit(int reg, int bit, int state) {
        uint8_t val = SPI_read(reg);
        if (state == 0) {
            val = val & ~(0x01 << bit);
        } else {
            val = val | (0x01 << bit);
        }
        SPI_write(reg, val);
    }

void freefall_electicimp(){
  
  uint8_t dataToWrite = 0;
  
  SPI_writeBit(LIS3DH_CTRL_REG3, 6, 1);
  
  int _range = 2; 
    
  uint8_t threshold = (((0.4 * 1.0) / (_range)) * 127);
  dataToWrite = 0;
  dataToWrite = (threshold & 0x7f);
  SPI_write(LIS3DH_INT1_THS, dataToWrite);
  
  dataToWrite = 0;
  dataToWrite = (2 & 0x7f);
  SPI_write(LIS3DH_INT1_DURATION, dataToWrite);
  
  uint8_t options = LIS3DH_AOI | LIS3DH_X_LOW | LIS3DH_Y_LOW | LIS3DH_Z_LOW;
  SPI_write(LIS3DH_INT1_CFG, options);
}

void actuate(uint16_t time){
 
  uint16_t j;

  for(j=0; j<time;j++){
//    GPIO_WriteHigh(GPIOA, GPIO_PIN_2);
    GPIO_WriteHigh(GPIOB, GPIO_PIN_4);
    delay(1); 
  }
  
  GPIO_WriteLow(GPIOB, GPIO_PIN_4); 
//  GPIO_WriteLow(GPIOA, GPIO_PIN_2);
  
}

void tap2()
{
    SPI_write(48, 0);
    SPI_write(50, 0);
    SPI_write(51, 0);
    SPI_write(56, 21);
    SPI_write(57, 0);
    SPI_write(58, 80);
    SPI_write(59, 8);
    SPI_write(60, 8);
    SPI_write(61, 16);
    SPI_write(38, 8);
    SPI_write(34, 128);
    SPI_write(37, 0);
    SPI_write(31, 0);
    SPI_write(32, 71);
    SPI_write(35, 136);
    SPI_write(46, 0);
    SPI_write(36, 8);
}


void blink_led(int times, int duration){
  for(int i = 0; i< times-1; i++){
    GPIO_WriteHigh(GPIOA, GPIO_PIN_2); 
    delay(duration);
    GPIO_WriteLow(GPIOA, GPIO_PIN_2); 
    delay(duration);
  }
    GPIO_WriteHigh(GPIOA, GPIO_PIN_2); 
    delay(duration);
    GPIO_WriteLow(GPIOA, GPIO_PIN_2); 
}